language: node_js 
node_js: stable

install: 
 - npm install -g gulp 
 - npm install

# - npm install -g gulp

script: 
 - hexo g

after_script: 
 - cd ./public 
 - git init 
 - git config user.name "Afowne" 
 - git config user.email "afowne@gmail.com"
 - git add . 
 - git commit -m "Update Readme docs with TRAVIS-CI."
 - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches: 
 only: 
  - master 
env: 
 global: 
  - GH_REF: github.com/afowne/hexo_one.git