language: node_js
node_js: stable
install:
- npm install -g gulp
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git checkout -b hexo-gen
- git config user.name "Afowne"
- git config user.email "afowne@gmail.com"
- git add .
- git commit -m "Update Readme docs to static html with TRAVIS-CI."
- git push --force --quiet "https://${gh_token}@${GH_REF}" hexo-gen:hexo-gen
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/afowne/hexo_one.git
before_install:
- openssl aes-256-cbc -K $encrypted_2e3e2869fa2d_key -iv $encrypted_2e3e2869fa2d_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
